# # Reference files

base:
        dir: "/exports/eddie/scratch/jbarang/"
        run: "TEST"
ref_mm10:
        referenceFolder: "/exports/igmm/eddie/ponting-lab/JTB/mm10-ERCC/"
        # the genome file
        genome: "mm10-ERCC.fasta"
        # the STAR index dir
        starIndex: "mm10-ERCC/star/"
        # gtf file with transcripts
        annotation: "genes/genes.gtf"
        transcriptome: "transcripts.fa"
params:
        star: 
                readFilesCommand: "zcat"
                outSAMtype: "BAM SortedByCoordinate"
                outSAMattributes: "All"
                outSAMunmapped: "Within KeepPairs"
                quantMode: "TranscriptomeSAM GeneCounts"

