#. /etc/profile.d/modules.sh
#MODULEPATH=$MODULEPATH:/exports/igmm/software/etc/el7/modules

TRIM: "/nfs/software/marioni/Trimmomatic-0.36/trimmomatic-0.36.jar"
Tparam: "ILLUMINACLIP:/nfs/software/marioni/Trimmomatic-0.36/adapters/TruSeq3-PE.fa:1:30:10:1 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:75"

FQC: "/nfs/software/marioni/FastQC/fastqc"
STAR: "/nfs/software/marioni/STAR-2.5.3a/bin/Linux_x86_64_static/STAR"

FC: "/nfs/software/marioni/subread-1.6.0-Linux-x86_64/bin/featureCounts"
SALMON: "/nfs/software/marioni/Salmon-latest_linux_x86_64/bin/salmon"