import os

# this Snakefile makes certain assumptions about the file directory structure
# namely that there is a directory called fastq, that contains the fastq files
# further these fastq files must themselves have a format <file_name>.fastq.1.gz

FASTQ_DIR = "fastq/"

FASTQ, = glob_wildcards(os.path.join(FASTQ_DIR, '{sample,[^/]+}.fastq.1.gz'))
READS = [1, 2]
PATTERN_R1 = '{sample}.fastq.1.gz'
PATTERN_R2 = '{sample}.fastq.2.gz'

###############################
## Finish with a dummy task  ##
###############################

rule touch_out:
    input:
        expand('fastqc.dir/{sample}.{read}_fastqc.html', sample=FASTQ, read=READS)
    output:
        'fastqc.dir/test.txt'
    shell:
        'echo {input} >> {output}'

#######################################
## Read trimming and adaptor removal ##
#######################################
        
rule trim_adaptor:
    """
    Use trimmomatic to remove adaptor contamination and quality trim reads to a minimum length
    NB: this should be user-configured to handle different read lengths and trimming parameter values
    """
    input:
        R1 = os.path.join(FASTQ_DIR, PATTERN_R1),
        R2 = os.path.join(FASTQ_DIR, PATTERN_R2)
    output:
        R1 = "trimmed/trimmed-{sample}.fastq.1.gz",
        R2 = "trimmed/trimmed-{sample}.fastq.2.gz"
    threads: 8
    log:
        "logs/trim_adaptor/{sample}.log"
    shell:
        # trimmomatic needs to be in the PATH variable ideally, and the adaptor sequences in a common location
        # I think to make this as universal as possible I'll need to create a script that executes trimmomatic on
        # the command line with the relevant options - still needs to know where the trimmomatic binary is though
        # is this a job for conda?  Could we deploy this pipeline as a conda environment, that way we can
        # control the paths to software binaries...
        """java -jar /nfs/software/marioni/Trimmomatic-0.36/trimmomatic-0.36.jar PE -threads {threads} -phred33 {input.R1} {input.R2} {output.R1} {output.R1}.unpaired {output.R2} {output.R2}.unpaired \
        ILLUMINACLIP:/nfs/software/marioni/Trimmomatic-0.36/adapters/TruSeq3-PE.fa:1:30:10:1 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:75"""


#######################################
## Run FastQC on trimmed FASTQ files ##
#######################################
rule run_fastqc:
    """
    Run FastQC to generate a html report with a selection of QC modules
    """
    input:
        "trimmed/trimmed-{sample}.fastq.{read}.gz"
    output:
        "fastqc.dir/{sample}.{read}_fastqc.html"
    threads: 4
    shell:
        "fastqc  -o fastqc.dir/  --noextract  --threads {threads}  --dir temp.dir/  {input}" 
